openapi: 3.0.3
info:
  title: vacanciesShort API
  description: API для получения сокращеного списка вакансий
  version: 1.0.0
servers:
  - url: http://localhost:3001

paths:
  /vacancies-short:
    get:
      summary: Получить сокращённый список вакансий
      tags:
        - Vacancies
      responses:
        "200":
          description: Массив сокращённых вакансий
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Vacancy"

components:
  schemas:
    Vacancy:
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: Помощник компьютерного мастера
        wages:
          type: array
          minItems: 1
          maxItems: 2
          items:
            type: string
          example: ["30 000", "40 000"]
        details:
          type: array
          items:
            type: string
          example:
            - Полный день
            - Выплаты 2 раза в месяц
            - Без опыта
        description:
          type: string
          example: >
            Мы с радостью примем помощника компьютерного мастера в свою компанию. Лучшая Сеть комиссионных магазинов ЦентрКОМ и Мегабайк...
